name: Build, Test and Deploy Docker Image

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t yourusername/tag_app:latest .

    - name: Run tests
      run: |
        docker run --rm yourusername/tag_app:latest python -m unittest discover -s tests  # Ajuste conforme necessário

    - name: Push Docker image
      if: success()  # Apenas faz o push se os testes forem bem-sucedidos
      run: |
        docker push yourusername/tag_app:latest
