name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag geraldoti2022/app-tags:latest
          docker tag geraldoti2022/app-tags:latest geraldoti2022/app-tags:$(date +%s)  # Optional: Add timestamp tag
      
      - name: Push the Docker image
        run: |
          docker push geraldoti2022/app-tags:latest
          docker push geraldoti2022/app-tags:$(date +%s)  # Optional: Push the timestamp tag
